-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 17:00:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_SIGECU
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_SIGECU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_SIGECU` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `DB_SIGECU` ;

-- -----------------------------------------------------
-- Table `DB_SIGECU`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`instructor` (
  `idinstructor` INT NOT NULL AUTO_INCREMENT,
  `iNombre` VARCHAR(45) NOT NULL,
  `iPaterno` VARCHAR(45) NULL,
  `iMaterno` VARCHAR(45) NULL,
  `Carrera` VARCHAR(45) NULL,
  `Especialidad` VARCHAR(45) NULL,
  `iEmail` VARCHAR(45) NULL,
  `iTelefono` VARCHAR(45) NULL,
  `iDireccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idinstructor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`cursos` (
  `idcursos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(45) NULL,
  `fechaInicio` VARCHAR(45) NULL,
  `fechaFin` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `i_idinstructor` INT NOT NULL,
  PRIMARY KEY (`idcursos`),
  INDEX `fk_cursos_instructor1_idx` (`i_idinstructor` ASC),
  CONSTRAINT `fk_cursos_instructor1`
    FOREIGN KEY (`i_idinstructor`)
    REFERENCES `DB_SIGECU`.`instructor` (`idinstructor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`evaluaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`evaluaciones` (
  `idevaluacion` INT NOT NULL AUTO_INCREMENT,
  `c_idcursos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `idAlumno` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `tiempo` TIME NOT NULL,
  PRIMARY KEY (`idevaluacion`),
  INDEX `fk_evaluaciones_cursos1_idx` (`c_idcursos` ASC),
  CONSTRAINT `fk_evaluaciones_cursos1`
    FOREIGN KEY (`c_idcursos`)
    REFERENCES `DB_SIGECU`.`cursos` (`idcursos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`preguntas` (
  `idpregunta` INT NOT NULL AUTO_INCREMENT,
  `e_idevaluacion` INT NOT NULL,
  `idEvaluacion` INT NOT NULL,
  `Pregunta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpregunta`),
  INDEX `fk_preguntas_evaluaciones1_idx` (`e_idevaluacion` ASC),
  CONSTRAINT `fk_preguntas_evaluaciones1`
    FOREIGN KEY (`e_idevaluacion`)
    REFERENCES `DB_SIGECU`.`evaluaciones` (`idevaluacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`Respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`Respuestas` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `p_idpregunta` INT NOT NULL,
  `Respuesta` VARCHAR(45) NOT NULL,
  `Solucion` VARCHAR(45) NOT NULL,
  `Puntaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRespuesta`),
  INDEX `fk_Respuestas_preguntas1_idx` (`p_idpregunta` ASC),
  CONSTRAINT `fk_Respuestas_preguntas1`
    FOREIGN KEY (`p_idpregunta`)
    REFERENCES `DB_SIGECU`.`preguntas` (`idpregunta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`templetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`templetes` (
  `idtempletes` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(150) NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idtempletes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `p_idPais` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  INDEX `fk_ciudad_pais1_idx` (`p_idPais` ASC),
  CONSTRAINT `fk_ciudad_pais1`
    FOREIGN KEY (`p_idPais`)
    REFERENCES `DB_SIGECU`.`pais` (`idPais`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`promociones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`promociones` (
  `idpromociones` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idpromociones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`eventos` (
  `idevento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaInicio` DATE NULL,
  `descripcion` VARCHAR(45) NULL,
  `programa` VARCHAR(45) NULL,
  `i_idinstructor` INT NOT NULL,
  `lugar` VARCHAR(45) NULL,
  `c_idCiudad` INT NOT NULL,
  `capacidad` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `estatus` VARCHAR(45) NULL,
  `costo` VARCHAR(45) NULL,
  `t_idtempletes` INT NOT NULL,
  `p_idpromociones` INT NOT NULL,
  PRIMARY KEY (`idevento`),
  INDEX `fk_eventos_instructor1_idx` (`i_idinstructor` ASC),
  INDEX `fk_eventos_templetes1_idx` (`t_idtempletes` ASC),
  INDEX `fk_eventos_ciudad1_idx` (`c_idCiudad` ASC),
  INDEX `fk_eventos_promociones1_idx` (`p_idpromociones` ASC),
  CONSTRAINT `fk_eventos_instructor1`
    FOREIGN KEY (`i_idinstructor`)
    REFERENCES `DB_SIGECU`.`instructor` (`idinstructor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eventos_templetes1`
    FOREIGN KEY (`t_idtempletes`)
    REFERENCES `DB_SIGECU`.`templetes` (`idtempletes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eventos_ciudad1`
    FOREIGN KEY (`c_idCiudad`)
    REFERENCES `DB_SIGECU`.`ciudad` (`idCiudad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eventos_promociones1`
    FOREIGN KEY (`p_idpromociones`)
    REFERENCES `DB_SIGECU`.`promociones` (`idpromociones`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`alumno` (
  `idalumno` INT NOT NULL AUTO_INCREMENT,
  `aNombre` VARCHAR(45) NOT NULL,
  `aPaterno` VARCHAR(45) NOT NULL,
  `aMaterno` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `e_idEmpresa` INT NOT NULL,
  `carrera` VARCHAR(45) NULL,
  `notebook` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalumno`),
  INDEX `fk_alumno_empresa1_idx` (`e_idEmpresa` ASC),
  CONSTRAINT `fk_alumno_empresa1`
    FOREIGN KEY (`e_idEmpresa`)
    REFERENCES `DB_SIGECU`.`empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`materiales` (
  `idmaterial` INT NOT NULL AUTO_INCREMENT,
  `mNombre` VARCHAR(45) NOT NULL,
  `mDescripcion` VARCHAR(45) NULL,
  `mRuta` VARCHAR(45) NULL,
  `c_idcursos` INT NOT NULL,
  PRIMARY KEY (`idmaterial`),
  INDEX `fk_materiales_cursos1_idx` (`c_idcursos` ASC),
  CONSTRAINT `fk_materiales_cursos1`
    FOREIGN KEY (`c_idcursos`)
    REFERENCES `DB_SIGECU`.`cursos` (`idcursos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `valor` DOUBLE NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `RCFexpide` VARCHAR(45) NOT NULL,
  `selloDigital` VARCHAR(45) NOT NULL,
  `lugar` VARCHAR(45) NULL,
  `fecha` DATE NOT NULL,
  `RFCrecibe` VARCHAR(45) NOT NULL,
  `valorLetra` VARCHAR(100) NULL,
  `certificadoDigital` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`pagos` (
  `idpagos` INT NOT NULL AUTO_INCREMENT,
  `f_idfactura` INT NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`idpagos`),
  INDEX `fk_pagos_factura1_idx` (`f_idfactura` ASC),
  CONSTRAINT `fk_pagos_factura1`
    FOREIGN KEY (`f_idfactura`)
    REFERENCES `DB_SIGECU`.`factura` (`idfactura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`alumno_has_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`alumno_has_eventos` (
  `a_idalumno` INT NOT NULL AUTO_INCREMENT,
  `e_idevento` INT NOT NULL,
  PRIMARY KEY (`a_idalumno`, `e_idevento`),
  INDEX `fk_alumno_has_eventos_eventos1_idx` (`e_idevento` ASC),
  INDEX `fk_alumno_has_eventos_alumno1_idx` (`a_idalumno` ASC),
  CONSTRAINT `fk_alumno_has_eventos_alumno1`
    FOREIGN KEY (`a_idalumno`)
    REFERENCES `DB_SIGECU`.`alumno` (`idalumno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alumno_has_eventos_eventos1`
    FOREIGN KEY (`e_idevento`)
    REFERENCES `DB_SIGECU`.`eventos` (`idevento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`alumno_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`alumno_has_cursos` (
  `a_idalumno` INT NOT NULL,
  `c_idcursos` INT NOT NULL,
  PRIMARY KEY (`a_idalumno`, `c_idcursos`),
  INDEX `fk_alumno_has_cursos_cursos1_idx` (`c_idcursos` ASC),
  INDEX `fk_alumno_has_cursos_alumno1_idx` (`a_idalumno` ASC),
  CONSTRAINT `fk_alumno_has_cursos_alumno1`
    FOREIGN KEY (`a_idalumno`)
    REFERENCES `DB_SIGECU`.`alumno` (`idalumno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alumno_has_cursos_cursos1`
    FOREIGN KEY (`c_idcursos`)
    REFERENCES `DB_SIGECU`.`cursos` (`idcursos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`cursos_has_pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`cursos_has_pagos` (
  `c_idcursos` INT NOT NULL AUTO_INCREMENT,
  `p_idpagos` INT NOT NULL,
  `promocion` DOUBLE NOT NULL,
  PRIMARY KEY (`c_idcursos`, `p_idpagos`),
  INDEX `fk_cursos_has_pagos_pagos1_idx` (`p_idpagos` ASC),
  INDEX `fk_cursos_has_pagos_cursos1_idx` (`c_idcursos` ASC),
  CONSTRAINT `fk_cursos_has_pagos_cursos1`
    FOREIGN KEY (`c_idcursos`)
    REFERENCES `DB_SIGECU`.`cursos` (`idcursos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cursos_has_pagos_pagos1`
    FOREIGN KEY (`p_idpagos`)
    REFERENCES `DB_SIGECU`.`pagos` (`idpagos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`eventos_has_pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`eventos_has_pagos` (
  `e_idevento` INT NOT NULL AUTO_INCREMENT,
  `p_idpagos` INT NOT NULL,
  PRIMARY KEY (`e_idevento`, `p_idpagos`),
  INDEX `fk_eventos_has_pagos_pagos1_idx` (`p_idpagos` ASC),
  INDEX `fk_eventos_has_pagos_eventos1_idx` (`e_idevento` ASC),
  CONSTRAINT `fk_eventos_has_pagos_eventos1`
    FOREIGN KEY (`e_idevento`)
    REFERENCES `DB_SIGECU`.`eventos` (`idevento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eventos_has_pagos_pagos1`
    FOREIGN KEY (`p_idpagos`)
    REFERENCES `DB_SIGECU`.`pagos` (`idpagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`diploma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`diploma` (
  `iddiploma` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddiploma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`pre-inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`pre-inscripcion` (
  `idpre-inscripcion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `e_idEmpresa` INT NOT NULL,
  `carrera` VARCHAR(45) NULL,
  `confirmar` VARCHAR(45) NULL,
  PRIMARY KEY (`idpre-inscripcion`),
  INDEX `fk_pre-inscripcion_empresa1_idx` (`e_idEmpresa` ASC),
  CONSTRAINT `fk_pre-inscripcion_empresa1`
    FOREIGN KEY (`e_idEmpresa`)
    REFERENCES `DB_SIGECU`.`empresa` (`idEmpresa`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`alumno_has_diploma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`alumno_has_diploma` (
  `a_idalumno` INT NOT NULL,
  `d_iddiploma` INT NOT NULL,
  PRIMARY KEY (`a_idalumno`, `d_iddiploma`),
  INDEX `fk_alumno_has_diploma_diploma1_idx` (`d_iddiploma` ASC),
  INDEX `fk_alumno_has_diploma_alumno1_idx` (`a_idalumno` ASC),
  CONSTRAINT `fk_alumno_has_diploma_alumno1`
    FOREIGN KEY (`a_idalumno`)
    REFERENCES `DB_SIGECU`.`alumno` (`idalumno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alumno_has_diploma_diploma1`
    FOREIGN KEY (`d_iddiploma`)
    REFERENCES `DB_SIGECU`.`diploma` (`iddiploma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`pre-inscripcion_has_pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`pre-inscripcion_has_pagos` (
  `p_idpre-inscripcion` INT NOT NULL AUTO_INCREMENT,
  `p_idpagos` INT NOT NULL,
  PRIMARY KEY (`p_idpre-inscripcion`, `p_idpagos`),
  INDEX `fk_pre-inscripcion_has_pagos_pagos1_idx` (`p_idpagos` ASC),
  INDEX `fk_pre-inscripcion_has_pagos_pre-inscripcion1_idx` (`p_idpre-inscripcion` ASC),
  CONSTRAINT `fk_pre-inscripcion_has_pagos_pre-inscripcion1`
    FOREIGN KEY (`p_idpre-inscripcion`)
    REFERENCES `DB_SIGECU`.`pre-inscripcion` (`idpre-inscripcion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pre-inscripcion_has_pagos_pagos1`
    FOREIGN KEY (`p_idpagos`)
    REFERENCES `DB_SIGECU`.`pagos` (`idpagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`perfil` (
  `idPerfil` INT NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SIGECU`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SIGECU`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `idPerfil` INT NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `userPass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_usuarios_perfil1_idx` (`idPerfil` ASC),
  CONSTRAINT `fk_usuarios_perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `DB_SIGECU`.`perfil` (`idPerfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
